version: '3'

services:
  epay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4560:4560"
    environment:
      - CR_EPAY_DEBUG=false
      - CR_EPAY_LISTEN=:4560
      # 直接定义环境变量，而不是使用 .env 文件
      - CR_EPAY_BASE=http://localhost:4560
      - CR_EPAY_CLOUDREVE_KEY=your_cloudreve_key_here
      - CR_EPAY_EPAY_PARTNER_ID=your_partner_id_here
      - CR_EPAY_EPAY_KEY=your_epay_key_here
      - CR_EPAY_EPAY_ENDPOINT=https://your-epay-endpoint.com/submit.php
      - CR_EPAY_EPAY_PURCHASE_TYPE=alipay
      - CR_EPAY_REDIS_ENABLED=true
      - CR_EPAY_REDIS_SERVER=redis:6379
      - CR_EPAY_REDIS_PASSWORD=
      - CR_EPAY_REDIS_DB=0
      - CR_EPAY_AUTO_SUBMIT=true
      # USDTMore 配置
      - CR_EPAY_USDTMORE_ENABLED=true
      # 根据独角数卡的实现，完整的 API 端点应该是基础 URL
      - CR_EPAY_USDTMORE_API_ENDPOINT=https://us.wkk.su
      - CR_EPAY_USDTMORE_AUTH_TOKEN=jWSJrZs5eT11TpWCEyAc78jAwxh9ReA8
      - CR_EPAY_USDTMORE_DEFAULT_CHAIN=TRON
      # 是否只启用USDT支付（如果为true，将只显示USDT支付选项）
      - CR_EPAY_USDTMORE_ONLY=true
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - epay-network

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - epay-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  epay-network:
    driver: bridge
